package edu.eci.cvds.pbt.registry;

public enum RegisterResult {
        VALID , ERROR_YA_REGRISTADO, ERROR_IDENTIFICACION_NO_VALIDA, ERROR_EDAD_NO_VALIDA, ERROR_CIUDADANO_FALLECIDO,
        ERROR_NOMBRE_NO_VALIDO,ERROR_DOCUMENTO_YA_REGISTRADO,CERTIFICADO_VALIDO,CERTIFICADO_INVALIDO;
        
}